version: "3"

tasks:
  install:
    cmds:
      - uv sync
  lint:
    cmds:
      - uv run ruff check app tests alembic
      - uv run ruff format --check app tests alembic
      - uv run mypy app tests
  build:
    cmds:
      - uv run alembic upgrade head
      - uv export --output-file requirements.txt
  test:
    cmds:
      - uv run pytest --cov --cov-report=term --cov-report=xml
