
name: improved-tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: realworld_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install system build deps
        run: sudo apt-get update && sudo apt-get install -y libpq-dev python3-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pytest pytest-cov alembic
      - name: Configure env
        run: |
          echo "APP_ENV=test" >> $GITHUB_ENV
          echo "DATABASE_URL=postgresql+psycopg2://postgres:postgres@localhost:5432/realworld_test" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-please-change" >> $GITHUB_ENV
      - name: Run tests with coverage
        run: |
          mkdir -p reports
          pytest -q --maxfail=1 --cov=app --cov-branch --cov-report=xml:reports/coverage.xml --cov-report=term-missing --junitxml=reports/junit.xml
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports
