name: improved-tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: main
          POSTGRES_PASSWORD: main
          POSTGRES_DB: realworld_test
        ports:
          - 5434:5432
        options: >-
          --health-cmd="pg_isready -U main"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system build deps
        run: sudo apt-get update && sudo apt-get install -y libpq-dev python3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Core app deps (explicit to avoid build step)
          pip install fastapi "uvicorn[standard]" sqlalchemy psycopg2-binary psycopg pydantic[email] pydantic-settings httpx python-jose passlib[bcrypt] python-slugify
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pytest pytest-cov alembic

      - name: Configure env
        run: |
          echo "APP_ENV=test" >> $GITHUB_ENV
          # DSNs (set BOTH async & sync to be safe)
          echo "DATABASE_URL=postgresql+psycopg://main:main@localhost:5434/realworld_test" >> $GITHUB_ENV
          echo "ASYNC_DATABASE_URL=postgresql+psycopg://main:main@localhost:5434/realworld_test" >> $GITHUB_ENV
          # Split vars (for configs that compose the DSN from parts)
          echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
          echo "POSTGRES_PORT=5434" >> $GITHUB_ENV
          echo "POSTGRES_DB=realworld_test" >> $GITHUB_ENV
          echo "POSTGRES_USER=main" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=main" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-please-change" >> $GITHUB_ENV

      - name: Wait for Postgres to accept connections
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -p 5434 -U main && break
            sleep 1
          done

      - name: Run tests with coverage
        run: |
          mkdir -p reports
          pytest -q --maxfail=1 --cov=app --cov-branch --cov-report=xml:reports/coverage.xml --cov-report=term-missing --junitxml=reports/junit.xml

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports
